### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/evaluacion-intermedia-modulo-1-azaharamg#2]
Muy buen trabajo!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Score: 28 / 45
- [x] CARPETAS > CSS: La ruta del fichero CSS debe empezar por `./`.
- [x] CARPETAS > CSS: La ruta del fichero CSS debe estar en una subcarpeta del proyecto
- [x] CARPETAS > IMG: La ruta de la imagen debe empezar por `./`.
- [x] CARPETAS > IMG: La ruta de la imagen debe estar en una subcarpeta del proyecto
- [x] CARPETAS > CSS: La ruta del fichero CSS debe empezar por `./`.
- [x] HTML > LINK: El fichero de fuentes debe estar antes que nuestro fichero de estilos para que ningún fichero de estilos externo sobre escriba los nuestros.
- [x] HTML > HEADER: El logo debe tener el atributo title.
- [x] HTML > MENÚ: Los textos de los enlaces deben ser "Blog" y "Contacto" en el HTML. Debemos ponerlos en mayúsculas con CSS.
- [x] HTML > MENÚ: Los enlaces deben tener el atributo `title`.
- [x] HTML > MAIN: Necesitamos una etiqueta `h1`.
- [x] HTML > HTML: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS.
- [x] CSS > COLOR: El color del h1 debe ser blanco
- [x] CSS > FONT-FAMILY: Usa la herencia, ponle la fuente Rubik al `body` para que la hereden el menú y el h1.
- [x] CSS > FONT-FAMILY: La fuente del h1 debe ser Rubik
- [x] CSS > FONT-SIZE: El tamaño del h1 en móvil debe ser 30px.
- [x] CSS > FONT-SIZE: El tamaño del h1 en tablet debe ser 40px.
- [x] CSS > CLASES: No se deben utilizar etiquetas CSS ni ids como selectores, salvo `a`, `html` y `body`.

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe todas las clases CSS en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits tambien tienen que ser en inglés empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te enjaca dímelo cuanto antes por favor.

**Comment by azaharamg** [comment]
Buenas Miguel!!
He corregido los puntos que he visto que estaban mal, otros me parece que están bien pero puedo estar equivocándome, por si le puedes echar un ojo :sweat_smile: 

> CARPETAS > CSS: La ruta del fichero CSS debe empezar por ./.

Corregido

> CARPETAS > CSS: La ruta del fichero CSS debe estar en una subcarpeta del proyecto

Estaba correcto

> CARPETAS > IMG: La ruta de la imagen debe empezar por ./.

Corregido

> CARPETAS > IMG: La ruta de la imagen debe estar en una subcarpeta del proyecto

Estaba correcto

>  CARPETAS > CSS: La ruta del fichero CSS debe empezar por ./.

Duplicado, corregido en el anterior punto

> HTML > LINK: El fichero de fuentes debe estar antes que nuestro fichero de estilos para que ningún fichero de estilos externo sobre escriba los nuestros.

Corregido

> HTML > HEADER: El logo debe tener el atributo title.

Corregido

> HTML > MENÚ: Los textos de los enlaces deben ser "Blog" y "Contacto" en el HTML. Debemos ponerlos en mayúsculas con CSS.

Corregido

> HTML > MENÚ: Los enlaces deben tener el atributo title.

Corregido

> HTML > MAIN: Necesitamos una etiqueta h1.

Corregido

> HTML > HTML: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS.

Corregido

> CSS > COLOR: El color del h1 debe ser blanco

Estaba correcto

> CSS > FONT-FAMILY: Usa la herencia, ponle la fuente Rubik al body para que la hereden el menú y el h1.

Estaba correcto

> CSS > FONT-FAMILY: La fuente del h1 debe ser Rubik

Estaba correcto

> CSS > FONT-SIZE: El tamaño del h1 en móvil debe ser 30px.

Estaba correcto

> CSS > FONT-SIZE: El tamaño del h1 en tablet debe ser 40px.

Estaba correcto

> CSS > CLASES: No se deben utilizar etiquetas CSS ni ids como selectores, salvo a, html y body.

Solo utilizo `body`

Muchas gracias!!! ya me dices :)

**Comment by migueldelmazo** [comment]
Hola @azaharamg,

voy a revisar los puntos que me dices. Muchas gracias por el feedback.

He vuelto a pasar el corrector y me dice lo siguiente:

- [ ] HTML > MENÚ: Los enlaces deben tener el atributo `title`.
- [ ] CSS > CLASES: No se deben utilizar etiquetas CSS ni ids como selectores, salvo `a`, `html` y `body`.
- [ ] CSS > ESTILOS REPETIDOS: Hay estilos repetidos en las media queries que no son necesarios, es mejor quitarlos. `.header { display: flex }`, `.header { position: fixed }`, `.header { align-items: center }`, `.header { background: white }`, `.header { width: 100% }`, `.nav__items { list-style-type: none }`

Buen trabajo.

**Comment by azaharamg** [comment]
Actualizado :)
